version: '2'
services:
    hibernate2ndcache-app:
        image: hibernate2ndcache
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hibernate2ndcache-mysql:3306/hibernate2ndcache?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hibernate2ndcache-mysql:
        extends:
            file: mysql.yml
            service: hibernate2ndcache-mysql
